### ISSUE TITLE
Unable to enable addon, ver 1.0.2, blender ver 2.73

### ISSUE THREAD

**Issue by animk** [CGCookie/retopology-polystrips#59]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\blender-2.73-windows64\2.73\scripts\modules\addon_utils.py", line 299, in enable
    mod = **import**(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.73\scripts\addons\retopology-polystrips-master__init__.py", line 56, in <module>
    from lib import common_utilities
ImportError: cannot import name 'common_utilities'

**Comment by Bernard-Cousin** [comment]
got the same

**Comment by carter2422** [comment]
@Bernard-Cousin which version of RetopoFlow and which version of Blender? RetopoFlow v1.1.0 requires Blender 2.75

**Comment by Bernard-Cousin** [comment]
thanks for answering.
I use blender 2.76 with polystrips 1.0.2

**Comment by ChrisStil** [comment]
I got the same issue with Polystrips 1.0.2 in Blender 2.76 (Polystrips 1.0.2 requires Blender 2.71). I'm working on ubuntu 14.04.

**Comment by carter2422** [comment]
Hey @ChrisStil, typically this has been fixed by simply restarting Blender after installing the add-on.

**Comment by ChrisStil** [comment]
The solution to restart blender seems to work only under Windows. It works fine under Windows, but under ubuntu 14.04, the fact to restart blender does not change anything, the error is still there and I can't activate the addon.  (tested on blender 2.74 and 2.76 with Polystrips 1.0.2). Do you maybe have an Idea where the Problem could come from under ubuntu?

**Comment by carter2422** [comment]
@ChrisStil this is likely due to the relative imports of python modules failing. We've since made many, many improvements to the import processes to ensure it works in all systems, but these changes are all in RetopoFlow, since Polystrips and Contours have been combined. 

Unfortunately we can longer maintain the stand alone Polystrips/Contours, but you can use them as RetopoFlow: https://github.com/CGCookie/retopoflow

If you've purchased Polystrips then you can upgrade to RetopoFlow for a discount (I'll just need your receipt email): https://cgcookiemarkets.com/all-products/retopoflow/
